# Generated by Django 4.0.1 on 2022-01-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_encurtado',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
